import type { Metadata } from "next";
import { Bakbak_One as FontSans } from "next/font/google";
import "@/styles/globals.css";
import Header from "@/components/layout/Header";
import { cn } from "@/lib/utils";
import Script from "next/script";
import Footer from "@/components/layout/Footer";
const fontSans = FontSans({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Vivianware - High Quality Cheats",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  products
}: Readonly<{
  children: React.ReactNode;
  products: React.ReactNode 
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <Header />
        
        <div>{children}</div>
        <div>{products}</div>
      <Footer/>

        <Script src="https://cdn.sellix.io/static/js/embed.js" />
      </body>
    </html>
  );
}
